image: maven:latest

stages:
  - build

build_job_1:
  stage: build
  script:
    - apt install git
    - git submodule update --init
    - mvnw clean package
  artifacts:
    paths:
      - target/*.jar
